# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Juš Lesjak
email: lesjak.jus@gmail.com

author_firstname: Juš
author_lastname: Lesjak
author_job: Programmer / Student
author_email: lesjak.jus@gmail.com
author_phone: 0038630260470
author_birth: 26 Sep 2001 - Kranj, SLOVENIA
author_address: Valjavčeva 33 - 4000 Kranj - SLOVENIA

cv_avatar: 
cv_description: Nek motovational 30 sec elevator pitch k se ga morm se zmislt.
cv_thankyou: Thank you!
cv_quote: “Whether you say, ‘I can’ or ‘I can’t,’ you’re right either way.”
cv_quote_author: Jordan Belfort

description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  CDESLAYR
github_url: https://github.com/CDESLAYR


collections:
  education:
  fragmetns:
  interests:
  portfolio:
  profileInfos:
  skills:
  socialmedia:
  work:

defaults:
  -
    scope:
      path: ""
      type: "education" 
    values:
      layout: "education"
  -
    scope:
      path: ""
      type: "fragments" 
    values:
      layout: "fragment"
  -
    scope:
      path: ""
      type: "interests" 
    values:
      layout: "interests"
  -
    scope:
      path: ""
      type: "portfolio" 
    values:
      layout: "portfolio"
  -
    scope:
      path: ""
      type: "profileInfos" 
    values:
      layout: "profile"
  -
    scope:
      path: ""
      type: "skills" 
    values:
      layout: "skills"
  -
    scope:
      path: ""
      type: "work" 
    values:
      layout: "work"
  -
    scope:
      path: ""
      type: "socialmedia" 
    values:
      layout: "socialmedia"
    
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed


# # Static files
# defaults:
#   - scope:
#       path: "assets/img"
#     values:
#       image: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
